---
- name: "Install from homebrew"
  homebrew:
    name:
      - node
      - mongodb
    state: present

- name: "Install from homebrew cask"
  homebrew_cask:
    name:
      - postman
      - google-chrome-canary
      - cyberduck
    state: present

- name: "Install from npm"
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
    with_items:
      - bower
      - gulp-cli
      - eslint
      - ember-cli
      - grunt-cli
