---
- name: "Install from homebrew"
  homebrew:
    name:
      - node
      - mongodb
    state: present
- name: "Install from homebrew cask"
  homebrew_cask:
    name:
      - postman
      - google-chrome-canary
      - cyberduck
    state: present

- name: "Install bower"
  npm:
    name: bower
    global: yes
    state: latest

- name: "Install gulp-cli"
  npm:
    name: gulp-cli
    global: yes
    state: latest

- name: "Install eslint"
  npm:
    name: eslint
    global: yes
    state: latest

- name: "Install ember-cli"
  npm:
    name: ember-cli
    global: yes
    state: latest

- name: "Install grunt-cli"
  npm:
    name: grunt-cli
    global: yes
    state: latest
